import * as functions from "firebase-functions/v1";
import * as admin from "firebase-admin";
import * as crypto from "crypto";
import { generateCareerVividModuleEmail, CareerVividEmailModule } from "./emailTemplateLibrary";
import {
  CAREERVIVID_SYSTEM_NOTIFICATION_FOOTER,
  canonicalCareerVividUrl,
  canonicalDashboardUrl,
  canonicalProfileUrl,
} from "./emailPolicy";

if (!admin.apps.length) {
  admin.initializeApp();
}

const db = admin.firestore();
const REGION = "us-west1";
const TEMPLATE_VERSION = "2026-05-29";

export type TransactionalEmailType =
  | "email_verification"
  | "password_reset"
  | "password_reset_confirmation"
  | "account_deletion_initialization";

type TransactionalEmailInput = {
  type: TransactionalEmailType;
  to: string;
  userName?: string;
  actionUrl?: string;
  deletionTargetDate?: Date;
  metadata?: Record<string, unknown>;
};

const getDisplayName = (user: admin.auth.UserRecord): string => {
  return user.displayName || user.email?.split("@")[0] || "there";
};

const formatDate = (date?: Date): string => {
  if (!date) return "30 days from today";
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "America/Chicago",
  }).format(date);
};

const sanitizeContinueUrl = (value: unknown, fallbackPath: string): string => {
  const fallback = canonicalCareerVividUrl(fallbackPath, { source: "transactional_email" });
  if (typeof value !== "string" || !value.trim()) return fallback;

  try {
    const url = new URL(value);
    const isAllowedHost =
      url.hostname === "careervivid.app" ||
      url.hostname.endsWith(".careervivid.app") ||
      url.hostname === "localhost" ||
      url.hostname === "127.0.0.1";
    return isAllowedHost ? url.toString() : fallback;
  } catch {
    return fallback;
  }
};

const hashEmailForLogs = (email: string): string => {
  return crypto.createHash("sha256").update(email).digest("hex").slice(0, 16);
};

const buildTransactionalEmail = (input: TransactionalEmailInput) => {
  const userName = input.userName || "there";
  const dashboardUrl = canonicalDashboardUrl("transactional_email");
  const profileUrl = canonicalProfileUrl("transactional_email");
  const modules: CareerVividEmailModule[] = [];
  let subject = "";
  let preheader = "";
  let text = "";

  if (input.type === "email_verification") {
    subject = "Verify your CareerVivid account";
    preheader = "Confirm your email address and open your CareerVivid workspace.";
    modules.push(
      {
        type: "hero",
        eyebrow: "Welcome to CareerVivid",
        title: "Confirm your workspace email",
        subtitle: "Verify this address so CareerVivid can protect your account and keep your job-search workspace connected.",
        variant: "milestone",
      },
      {
        type: "body",
        paragraphs: [
          "Your account is ready. Confirming your email helps us protect profile changes, resume data, saved jobs, and interview prep activity.",
          "After verification, you can open your dashboard and continue from the same workspace.",
        ],
      },
      {
        type: "checklist",
        title: "What unlocks next",
        items: [
          { title: "Profile continuity", body: "Keep resumes, saved roles, and application prep tied to the right account." },
          { title: "Secure account notices", body: "Receive required security and billing messages at this address." },
          { title: "Workspace setup", body: "Finish your profile and resume baseline when you return." },
        ],
      },
      {
        type: "cta",
        primary: { text: "Verify email", url: input.actionUrl || dashboardUrl },
        secondary: { text: "Open dashboard", url: dashboardUrl },
        helper: "This verification link is generated securely by Firebase Authentication.",
      }
    );
    text = `Verify your CareerVivid account: ${input.actionUrl || dashboardUrl}`;
  }

  if (input.type === "password_reset") {
    subject = "Reset your CareerVivid password";
    preheader = "Use this secure link to reset your password.";
    modules.push(
      {
        type: "hero",
        eyebrow: "Account security",
        title: "Reset your password",
        subtitle: "Use the secure link below to choose a new password for your CareerVivid account.",
        variant: "report",
      },
      {
        type: "body",
        paragraphs: [
          "We received a request to reset the password for this CareerVivid account.",
          "If you did not request this, you can ignore this email. Your current password will stay unchanged.",
        ],
      },
      {
        type: "status",
        title: "Secure reset link",
        body: "For your protection, this link is generated by Firebase Authentication and should only be used by you.",
        status: "warning",
      },
      {
        type: "cta",
        primary: { text: "Reset password", url: input.actionUrl || canonicalCareerVividUrl("/signin") },
        secondary: { text: "Open sign in", url: canonicalCareerVividUrl("/signin", { source: "password_reset_email" }) },
      }
    );
    text = `Reset your CareerVivid password: ${input.actionUrl || canonicalCareerVividUrl("/signin")}`;
  }

  if (input.type === "password_reset_confirmation") {
    subject = "Your CareerVivid password was updated";
    preheader = "This confirms your CareerVivid password changed successfully.";
    modules.push(
      {
        type: "hero",
        eyebrow: "Security receipt",
        title: "Password updated",
        subtitle: "This is a confirmation receipt for your CareerVivid account.",
        variant: "milestone",
      },
      {
        type: "status",
        title: "Change confirmed",
        body: "Your account password was updated. If you made this change, no action is needed.",
        status: "success",
      },
      {
        type: "body",
        paragraphs: [
          "If you did not update your password, reset it immediately and contact CareerVivid support so we can help secure your account.",
        ],
      },
      {
        type: "cta",
        primary: { text: "Open profile settings", url: profileUrl },
        secondary: { text: "Sign in", url: canonicalCareerVividUrl("/signin", { source: "password_receipt" }) },
      }
    );
    text = `Your CareerVivid password was updated. Profile settings: ${profileUrl}`;
  }

  if (input.type === "account_deletion_initialization") {
    const deletionDate = formatDate(input.deletionTargetDate);
    subject = "CareerVivid account deletion scheduled";
    preheader = `Your account is scheduled for permanent deletion on ${deletionDate}.`;
    modules.push(
      {
        type: "hero",
        eyebrow: "Account deletion",
        title: "Deletion window started",
        subtitle: "Your CareerVivid account is now in a 30-day soft-deletion retention period.",
        variant: "report",
      },
      {
        type: "status",
        title: "Retention deadline",
        body: `Permanent deletion is scheduled for ${deletionDate}. During this window, your account is disabled and your workspace data is retained only for account recovery and compliance handling.`,
        status: "critical",
        rows: [
          { label: "Status", value: "Soft deleted" },
          { label: "Permanent deletion date", value: deletionDate },
        ],
      },
      {
        type: "body",
        paragraphs: [
          "After the retention date, CareerVivid will permanently remove your Firebase Authentication record and associated workspace data.",
          "If this request was made by mistake, contact support before the deletion date.",
        ],
      },
      {
        type: "cta",
        primary: { text: "Contact support", url: canonicalCareerVividUrl("/contact", { source: "account_deletion" }) },
      }
    );
    text = `CareerVivid account deletion is scheduled for ${deletionDate}. Contact support before this date if this was a mistake.`;
  }

  return {
    subject,
    text,
    html: generateCareerVividModuleEmail({
      title: subject,
      preheader,
      userName,
      modules,
      footerText: CAREERVIVID_SYSTEM_NOTIFICATION_FOOTER,
    }),
  };
};

export async function queueTransactionalEmail(input: TransactionalEmailInput) {
  const email = buildTransactionalEmail(input);
  const mailRef = await db.collection("mail").add({
    to: input.to,
    message: email,
    notification: {
      category: "transactional",
      force: true,
    },
    transactional: {
      type: input.type,
      templateVersion: TEMPLATE_VERSION,
      metadata: input.metadata || {},
    },
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  return { mailId: mailRef.id, ...email };
}

export const sendTransactionalAuthEmail = functions
  .region(REGION)
  .https
  .onCall(async (data, context) => {
    const type = String(data?.type || "") as TransactionalEmailType;
    const continueUrl = sanitizeContinueUrl(data?.continueUrl, type === "password_reset" ? "/signin" : "/dashboard");

    if (type === "email_verification") {
      if (!context.auth?.uid) {
        throw new functions.https.HttpsError("unauthenticated", "Sign in before requesting verification email.");
      }

      const user = await admin.auth().getUser(context.auth.uid);
      if (!user.email) {
        throw new functions.https.HttpsError("failed-precondition", "Current user is missing an email address.");
      }

      const actionUrl = await admin.auth().generateEmailVerificationLink(user.email, { url: continueUrl });
      await queueTransactionalEmail({
        type,
        to: user.email,
        userName: getDisplayName(user),
        actionUrl,
        metadata: { uid: user.uid },
      });

      return { queued: true };
    }

    if (type === "password_reset") {
      const email = String(data?.email || "").trim().toLowerCase();
      if (!email || !email.includes("@")) {
        throw new functions.https.HttpsError("invalid-argument", "A valid email is required.");
      }

      const emailHash = hashEmailForLogs(email);

      try {
        const user = await admin.auth().getUserByEmail(email);
        const actionUrl = await admin.auth().generatePasswordResetLink(email, { url: continueUrl });
        await queueTransactionalEmail({
          type,
          to: email,
          userName: getDisplayName(user),
          actionUrl,
          metadata: { uid: user.uid },
        });
        functions.logger.info("Password reset email queued.", {
          emailHash,
          providerIds: user.providerData.map((provider) => provider.providerId),
        });
      } catch (error: any) {
        if (error?.code !== "auth/user-not-found") {
          throw error;
        }
        functions.logger.info("Password reset requested for unknown account.", { emailHash });
      }

      return { queued: true };
    }

    if (type === "password_reset_confirmation") {
      if (!context.auth?.uid) {
        throw new functions.https.HttpsError("unauthenticated", "Sign in before requesting a password change receipt.");
      }

      const user = await admin.auth().getUser(context.auth.uid);
      if (!user.email) {
        throw new functions.https.HttpsError("failed-precondition", "Current user is missing an email address.");
      }

      await queueTransactionalEmail({
        type,
        to: user.email,
        userName: getDisplayName(user),
        metadata: { uid: user.uid },
      });

      return { queued: true };
    }

    throw new functions.https.HttpsError("invalid-argument", "Unsupported transactional email type.");
  });
