
// Map of WeChat/common IM style text codes to Unicode Emojis
const EMOJI_MAP: Record<string, string> = {
    '[Party]': '🎉',
    '[Smile]': '🙂',
    '[Grimace]': '😬',
    '[Drool]': '🤤',
    '[Scowl]': '😠',
    '[CoolGuy]': '😎',
    '[Sob]': '😭',
    '[Shy]': '😳',
    '[Silent]': '😶',
    '[Sleep]': '😴',
    '[Cry]': '😢',
    '[Awkward]': '😅',
    '[Angry]': '😡',
    '[Tongue]': 'nP',
    '[Grin]': '😁',
    '[Surprise]': '😮',
    '[Frown]': '☹️',
    '[Ruthless]': '😈',
    '[Blush]': '😊',
    '[Scream]': '😱',
    '[Puke]': '🤮',
    '[Chuckle]': '🤭',
    '[Joyful]': '😂',
    '[Slight]': '🙂',
    '[Smug]': '😏',
    '[Hungry]': '😋',
    '[Drowsy]': '😪',
    '[Panic]': '😰',
    '[Sweat]': '😓',
    '[Laugh]': '😆',
    '[Commando]': '🫡',
    '[Determined]': '😤',
    '[Scold]': '🤬',
    '[Shocked]': '😲',
    '[Shhh]': '🤫',
    '[Dizzy]': '😵',
    '[Tormented]': '😣',
    '[Toasted]': '🥵',
    '[Skull]': '💀',
    '[Hammer]': '🔨',
    '[Wave]': '👋',
    '[Speechless]': '😶',
    '[NosePick]': '🤥',
    '[Clap]': '👏',
    '[Shame]': '😓',
    '[Trick]': '😜',
    '[Bah！L]': '👎',
    '[Bah！R]': '👎',
    '[Yawn]': '🥱',
    '[Pooh-pooh]': '💩',
    '[Shrunken]': '😣',
    '[TearingUp]': '🥹',
    '[Sly]': '😼',
    '[Kiss]': 'Mw',
    '[Wrath]': '💢',
    '[Whimper]': '🥺',
    '[Cleaver]': '🔪',
    '[Watermelon]': '🍉',
    '[Beer]': '🍺',
    '[Basketball]': '🏀',
    '[PingPong]': '🏓',
    '[Coffee]': '☕',
    '[Rice]': '🍚',
    '[Pig]': '🐷',
    '[Rose]': '🌹',
    '[Wilt]': '🥀',
    '[Lips]': '👄',
    '[Heart]': '❤️',
    '[BrokenHeart]': '💔',
    '[Cake]': '🎂',
    '[Lightning]': '⚡',
    '[Bomb]': '💣',
    '[Dagger]': '🗡️',
    '[Football]': '⚽',
    '[Ladybug]': '🐞',
    '[Poop]': '💩',
    '[Moon]': '🌙',
    '[Sun]': '☀️',
    '[Gift]': '🎁',
    '[Hug]': '🤗',
    '[Strong]': '💪',
    '[Weak]': '🥀',
    '[Shake]': '🤝',
    '[Victory]': '✌️',
    '[Admire]': '😍',
    '[Seduce]': '😘',
    '[Handshake]': '🤝',
    '[Hamster]': '🐹',
    '[RightHum]': '哼',
    '[LeftHum]': '哼',
    '[Ok]': '👌',
    '[No]': '🙅',
    '[Jump]': '💃',
    '[Tremble]': '🥶',
    '[Love]': '🫶',
    '[HighFive]': '🙌',
    '[Circle]': '⭕',
    '[Kotow]': '🙇',
    '[Turn]': '回头',
    '[Skip]': '跳绳',
    '[Facepalm]': '🤦',
    '[Hey]': '🙋',
    '[Smart]': '🤓',
    '[Spec]': '🕶️'
};

/**
 * Parses a string and replaces known [Code] blocks with Unicode Emojis.
 * Useful for displaying text from systems (like WeChat) that use bracket codes.
 */
export const parseTextWithEmojis = (text: string): string => {
    if (!text) return '';

    // Create a regular expression based on the keys
    // We escape the brackets for the regex
    return text.replace(/\[[^\]]+\]/g, (match) => {
        return EMOJI_MAP[match] || match;
    });
};
