/**
 * Regenerates the quest-route module consumed by the `generateSitemap`
 * Cloud Function (functions/src/seo/generateSitemap.ts).
 *
 * The LIVE sitemap at /sitemap.xml is served by that function (static routes
 * + fresh community posts + these quest routes). Do NOT create a static
 * public/sitemap.xml — Firebase Hosting serves static files before rewrites,
 * which would silently shadow the function.
 *
 * Run after adding interview guides, then deploy functions:
 *   node scripts/generate-sitemap.mjs
 *   firebase deploy --only functions:generateSitemap
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const OUT_PATH = path.join(ROOT, 'functions', 'src', 'seo', 'questRoutes.generated.ts');

const index = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'interview-guides', '_index.json'), 'utf-8'));
const slugs = Object.values(index)
    .filter((entry) => entry && typeof entry === 'object' && entry.company && entry.slug)
    .map((entry) => entry.slug)
    .sort();

fs.writeFileSync(OUT_PATH, [
    '// AUTO-GENERATED by scripts/generate-sitemap.mjs — do not edit by hand.',
    `// ${slugs.length} guest-browsable company quest routes (/quest/{slug}).`,
    '',
    'export const QUEST_ROUTE_SLUGS: string[] = [',
    ...slugs.map((slug) => `    ${JSON.stringify(slug)},`),
    '];',
    '',
].join('\n'));

console.log(`questRoutes.generated.ts written with ${slugs.length} slugs`);
console.log('Next: firebase deploy --only functions:generateSitemap');
