import { Type } from "@google/genai";
import { Tool } from "../Tool.js";
import chalk from "chalk";
import { generateCoverLetter, listCoverLetters, resumesList } from "../../api.js";

function getLinkUrl(path: string): string {
    const isDev = process.env.NODE_ENV === "development" || process.env.CV_API_URL?.includes("localhost");
    return isDev ? `http://localhost:3000${path}` : `https://careervivid.app${path}`;
}

const generateCoverLetterTool: Tool = {
    name: "generate_cover_letter",
    description: "Generates a highly tailored cover letter based on a user's resume and a specific job description. This saves the cover letter privately in their account (it does NOT publish it as an article).",
    parameters: {
        type: Type.OBJECT,
        properties: {
            jobTitle: { type: Type.STRING, description: "The job title to tailor the cover letter for" },
            companyName: { type: Type.STRING, description: "The company name to tailor the cover letter for" },
            jobDescription: { type: Type.STRING, description: "The job description to tailor the cover letter against" },
            resumeId: { type: Type.STRING, description: "Optional IDEAL resume ID to use. If omitted, it will pick their most recently updated resume." }
        },
        required: ["jobTitle", "companyName", "jobDescription"]
    },
    execute: async (args: { jobTitle: string; companyName: string; jobDescription: string; resumeId?: string }) => {
        try {
            console.log(chalk.blue(`\nGenerating cover letter for ${args.jobTitle} at ${args.companyName}...`));

            let currentResumeId = args.resumeId;
            if (!currentResumeId) {
                const resumesRes = await resumesList();
                if ("isError" in resumesRes) {
                    return `Failed to fetch user's resumes: ${resumesRes.message}`;
                }
                const resumes = resumesRes.resumes;
                if (!resumes || resumes.length === 0) {
                    return "User has no resumes in CareerVivid. They must upload one first.";
                }
                currentResumeId = resumes[0].id;
            }

            const res = await generateCoverLetter({
                resumeId: currentResumeId,
                jobTitle: args.jobTitle,
                companyName: args.companyName,
                jobDescription: args.jobDescription
            });

            if ("isError" in res) {
                return `Failed to generate cover letter: ${res.message}`;
            }

            const coverLetter = res.coverLetter;
            const dashboardUrl = getLinkUrl("/dashboard/jobs");

            return `✅ Successfully generated a cover letter for ${args.jobTitle} at ${args.companyName}.
It has been privately saved to the user's account.

Instruct the user they can view it in their dashboard under "Application Materials":
${dashboardUrl}

Here is a preview of the content:
${coverLetter.content ? coverLetter.content.substring(0, 500) + '...' : ''}`;
        } catch (err: any) {
            return `Error generating cover letter: ${err.message}`;
        }
    }
};

const listCoverLettersTool: Tool = {
    name: "list_cover_letters",
    description: "Lists all cover letters generated by the user recently.",
    parameters: {
        type: Type.OBJECT,
        properties: {
            jobId: { type: Type.STRING, description: "Filter by a specific job ID" }
        }
    },
    execute: async (args: { jobId?: string }) => {
        try {
            const res = await listCoverLetters(args.jobId);
            if ("isError" in res) {
                return `Failed to list cover letters: ${res.message}`;
            }

            const letters = res.coverLetters;
            if (letters.length === 0) {
                return "No cover letters found. You can generate one using generate_cover_letter.";
            }

            const format = letters.map(c => `ID: ${c.id}\nTitle: ${c.jobTitle} at ${c.companyName}\nDate: ${c.createdAt}`).join("\n\n");
            return `Found ${res.total} cover letter(s):\n\n${format}`;
        } catch (err: any) {
            return `Error listing cover letters: ${err.message}`;
        }
    }
};

export const ALL_COVERLETTER_TOOLS = [
    generateCoverLetterTool,
    listCoverLettersTool
];
